force-app/main/default/objects/AKS_SimpleObject__c/AKS_SimpleObject__c.object-meta.xml
<CustomObject>
    <label>AKS_SimpleObject</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AKSSimpleObjectNumber</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AKS_SimpleObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AKS_SimpleObject__c/fields/GenderIdentity__c.field-meta.xml
<CustomField>
    <fullName>GenderIdentity__c</fullName>
    <label>GenderIdentity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Nonbinary</fullName>
            </value>
            <value>
                <fullName>Not Listed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AKS_SimpleObject__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AKS_SimpleObject__c/fields/TelNo__c.field-meta.xml
<CustomField>
    <fullName>TelNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TelNo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AKS_LightningDatatable.cls
public with sharing class AKS_LightningDatatable {

    @AuraEnabled
    public static List<AKS_SimpleObject__c> getRecords(){

        List<AKS_SimpleObject__c> result = new List<AKS_SimpleObject__c>();
        try {
            result = [ SELECT Id, FirstName__c, LastName__c, Email__c, TelNo__c, GenderIdentity__c
                        FROM AKS_SimpleObject__c
                        ORDER BY CreatedDate
                        LIMIT 500
                        ];            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

    @AuraEnabled
    public static List<AKS_SimpleObject__c> getOffsetRecords(Integer limitSize, Integer offset){

        List<AKS_SimpleObject__c> result = new List<AKS_SimpleObject__c>();
        try {
            result = [ SELECT Id, FirstName__c, LastName__c, Email__c, TelNo__c, GenderIdentity__c
                        FROM AKS_SimpleObject__c
                        ORDER BY CreatedDate
                        LIMIT :limitSize
                        OFFSET :offset
                        ];            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

    @AuraEnabled
    public static void updateRecords( List<AKS_SimpleObject__c> records ){
        try {
            update records;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return;
    }

}