force-app/main/default/objects/AKS_SimpleObject__c/AKS_SimpleObject__c.object-meta.xml
<CustomObject>
    <label>AKS_SimpleObject</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AKSSimpleObjectNumber</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AKS_SimpleObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AKS_SimpleObject__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AKS_WireStandard.cls
/*
 * This class is used to for LWC Component 'aksWireStandard'
 */
public with sharing class AKS_WireStandard {

    @AuraEnabled(cacheable=true)
    public static AKS_SimpleObject__c getSimpleObject(String recordId){
        AKS_SimpleObject__c result = new AKS_SimpleObject__c();
        try {
            result = [SELECT Id, LastName__c, FirstName__c FROM AKS_SimpleObject__c WHERE Id = :recordId LIMIT 1].get(0);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

}